### ISSUE TITLE
Import new sqllite file

### ISSUE THREAD

**Issue by FerasAmara** [AlvaroFranco/AFSQLManager#3]
Hello @AlvaroFranco ,

I have an issue and don't know why it's happening, when I add a new SQLlite file like (newTest.sqlite) to your demo project instead of your file (test.sqlite), the performQuery block not working, the

if (sqlite3_prepare_v2(_database, [fixedQuery UTF8String], -1, &statement, nil) == SQLITE_OK) 

does not enter in the body.

Thank you.
Regards.

**Comment by AlvaroFranco** [comment]
Hi,

Did you make sure that you have imported your sql file into the project and have opened the new sql file with -openLocalDatabaseWithName:andStatusBlock?

Also, you should be able to check which SQLite status returns the query by adding a log with the sqlite3_prepare_v2

```
NSLog(@"%i",sqlite3_prepare_v2(_database, [fixedQuery UTF8String], -1, &statement, nil));
```

Here you have the status int correspondences:

#define SQLITE_OK           0   /\* Successful result _/
/_ beginning-of-error-codes _/
#define SQLITE_ERROR        1   /_ SQL error or missing database _/
#define SQLITE_INTERNAL     2   /_ Internal logic error in SQLite _/
#define SQLITE_PERM         3   /_ Access permission denied _/
#define SQLITE_ABORT        4   /_ Callback routine requested an abort _/
#define SQLITE_BUSY         5   /_ The database file is locked _/
#define SQLITE_LOCKED       6   /_ A table in the database is locked _/
#define SQLITE_NOMEM        7   /_ A malloc() failed _/
#define SQLITE_READONLY     8   /_ Attempt to write a readonly database _/
#define SQLITE_INTERRUPT    9   /_ Operation terminated by sqlite3_interrupt()_/
#define SQLITE_IOERR       10   /_ Some kind of disk I/O error occurred _/
#define SQLITE_CORRUPT     11   /_ The database disk image is malformed _/
#define SQLITE_NOTFOUND    12   /_ Unknown opcode in sqlite3_file_control() _/
#define SQLITE_FULL        13   /_ Insertion failed because database is full _/
#define SQLITE_CANTOPEN    14   /_ Unable to open the database file _/
#define SQLITE_PROTOCOL    15   /_ Database lock protocol error _/
#define SQLITE_EMPTY       16   /_ Database is empty _/
#define SQLITE_SCHEMA      17   /_ The database schema changed _/
#define SQLITE_TOOBIG      18   /_ String or BLOB exceeds size limit _/
#define SQLITE_CONSTRAINT  19   /_ Abort due to constraint violation _/
#define SQLITE_MISMATCH    20   /_ Data type mismatch _/
#define SQLITE_MISUSE      21   /_ Library used incorrectly _/
#define SQLITE_NOLFS       22   /_ Uses OS features not supported on host _/
#define SQLITE_AUTH        23   /_ Authorization denied _/
#define SQLITE_FORMAT      24   /_ Auxiliary database format error _/
#define SQLITE_RANGE       25   /_ 2nd parameter to sqlite3_bind out of range _/
#define SQLITE_NOTADB      26   /_ File opened that is not a database file _/
#define SQLITE_ROW         100  /_ sqlite3_step() has another row ready _/
#define SQLITE_DONE        101  /_ sqlite3_step() has finished executing */

Tell me which status it returns

**Comment by FerasAmara** [comment]
Hi @AlvaroFranco ,

Thanks for you reply, I made the log you sent to me, I got the Error (1)

Thanks again for your help.

**Comment by AlvaroFranco** [comment]
That could mean two things: you have syntax errors on the SQL you're trying to perform, or there's a problem locating your database. When you open your database it returns success? Also, please check for the syntax error on your SQL

**Comment by FerasAmara** [comment]
Yes when I use openLocalDatabaseWithName it returns success.
About the database syntax, I tried to copy you original database (test.sqlite) and renamed it to (testNew.sqlite) without any edit on it, I just copy the file from the finder window, and renamed it, then import it to the project (drag, drop), the result was the same, the database couldn't open.
I sent the application demo on you email (alvarofrancoayala@gmail.com), if you could help.
Thanks

**Comment by AlvaroFranco** [comment]
OK, I downloaded your project and detected the error. On the left side of Xcode, select your file, testNew.sqlite. Then, enable the Xcode right bar if you haven't done it previously and select (in this case) AFSQLManager-Demo as Target Membership

![screen shot 2014-06-24 at 10 29 45](https://cloud.githubusercontent.com/assets/1408186/3368831/f3140a8e-fb79-11e3-9911-2addce35fbd7.png)

In your app, just select your app target in that section.

Regards!

**Comment by FerasAmara** [comment]
Thank you @AlvaroFranco, I appreciate your help, all things are working now.

Regards.
